### ISSUE TITLE
请问数据的密码账号那些 配置文件在哪里啊？

### ISSUE THREAD

**Issue by wmxl** [lzhpo/lzhpo-shiro#2]
玩不好啊。。。

**Comment by wmxl** [comment]
为什么菜单管理那里修改了 网站没变化？

**Comment by lzhpo** [comment]
@wmxl 不好意思 一直没看到消息  数据库在sql文件夹下

**Comment by lzhpo** [comment]
@wmxl 您指的是？

**Comment by wmxl** [comment]
> @wmxl 您指的是？

不好意思，我比较菜。 我想知道springboot，菜单那里比如说添加了新的菜单和按钮了，如果按钮 url是一个网页，是不是应该直接就可以打开的？
如果我照着你的样子再弄一套新的从model到控制器到数据库的东西，是不是添加按钮了也可以直接链接到那个我自己新创建的网页？

**Comment by lzhpo** [comment]
> > @wmxl 您指的是？
> 
> 不好意思，我比较菜。 我想知道springboot，菜单那里比如说添加了新的菜单和按钮了，如果按钮 url是一个网页，是不是应该直接就可以打开的？
> 如果我照着你的样子再弄一套新的从model到控制器到数据库的东西，是不是添加按钮了也可以直接链接到那个我自己新创建的网页？

可以啊，随意折腾，如果对springboot不是很熟悉可以去b站找点视频学习一下。生命不息，折腾不止。另:你咋还不睡觉，大半夜的，会猝死哦。

**Comment by lzhpo** [comment]
> > > > @wmxl 您指的是？
> > > 
> > > 
> > > 不好意思，我比较菜。 我想知道springboot，菜单那里比如说添加了新的菜单和按钮了，如果按钮 url是一个网页，是不是应该直接就可以打开的？
> > > 如果我照着你的样子再弄一套新的从model到控制器到数据库的东西，是不是添加按钮了也可以直接链接到那个我自己新创建的网页？
> > 
> > 
> > 可以啊，随意折腾，如果对springboot不是很熟悉可以去b站找点视频学习一下。生命不息，折腾不止。另:你咋还不睡觉，大半夜的，会猝死哦。
> 
> 我再做毕设，来不及了。 。

兄弟 身体要紧  注意休息  早点睡吧

**Comment by wmxl** [comment]
> > > > > @wmxl 您指的是？
> > > > 
> > > > 
> > > > 不好意思，我比较菜。 我想知道springboot，菜单那里比如说添加了新的菜单和按钮了，如果按钮 url是一个网页，是不是应该直接就可以打开的？
> > > > 如果我照着你的样子再弄一套新的从model到控制器到数据库的东西，是不是添加按钮了也可以直接链接到那个我自己新创建的网页？
> > > 
> > > 
> > > 可以啊，随意折腾，如果对springboot不是很熟悉可以去b站找点视频学习一下。生命不息，折腾不止。另:你咋还不睡觉，大半夜的，会猝死哦。
> > 
> > 
> > 我再做毕设，来不及了。 。
> 
> 兄弟 身体要紧 注意休息 早点睡吧

好的
